export const MockJsonResult = {
  $id: "1",
  Result: {
    $id: "2",
    ActionResult: true,
    People: [
      {
        $id: "3",
        HasFirstNameAndLastName: true,
        Name: "black Black",
        AvatarToken: null,
        Mobile: null,
        Email: "black@starter.com",
        ChatMemberIdentifier: "ea893090-e092-48f4-9278-5cf69e0e4863",
        ID: 263,
        Role: 0,
        IsDeleted: false,
        LastLoginDateTime: "2020-10-27T15:54:09.9",
        Relationship: "Owner",
      },
      {
        $id: "4",
        HasFirstNameAndLastName: true,
        Name: "black pro",
        AvatarToken: null,
        Mobile: null,
        Email: "black@pro.com",
        ChatMemberIdentifier: "ae22d018-2732-4bb1-a2f7-3ec0c798d1b6",
        ID: 264,
        Role: 1,
        IsDeleted: true,
        LastLoginDateTime: "2021-01-06T16:54:36.647",
        Relationship: "Owner",
      },
      {
        $id: "5",
        HasFirstNameAndLastName: true,
        Name: "black 22",
        AvatarToken: null,
        Mobile: null,
        Email: "black@white.com",
        ChatMemberIdentifier: "8f2a7acc-eccc-407c-bce7-9e2c82b75252",
        ID: 265,
        Role: 1,
        IsDeleted: false,
        LastLoginDateTime: "2019-10-11T10:58:56.377",
        Relationship: "Owner",
      },
      {
        $id: "6",
        HasFirstNameAndLastName: true,
        Name: "stone white",
        AvatarToken: "58068d0a-0f77-4e99-a61d-33422d8cbe12.png",
        Mobile: "01234",
        Email: "stone@white.com",
        ChatMemberIdentifier: "efb5a0db-f893-40a9-8c0a-68b18f4cbf67",
        ID: 266,
        Role: 2,
        IsDeleted: false,
        LastLoginDateTime: "2021-02-09T10:34:01.8",
        Relationship: "Adviser",
      },
      {
        $id: "7",
        HasFirstNameAndLastName: false,
        Name: "guest",
        AvatarToken: null,
        Mobile: null,
        Email: "guest@email.com",
        ChatMemberIdentifier: "0d0773be-8b71-42c2-b9e6-50a122a4e644",
        ID: 355,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Wife",
      },
      {
        $id: "8",
        HasFirstNameAndLastName: true,
        Name: "ss ss",
        AvatarToken: "123",
        Mobile: null,
        Email: "ss@white.com",
        ChatMemberIdentifier: "71bb1931-26b6-4f38-a799-f1765ab1b946",
        ID: 384,
        Role: 4,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Adviser",
      },
      {
        $id: "9",
        HasFirstNameAndLastName: true,
        Name: "Baher Business",
        AvatarToken: null,
        Mobile: null,
        Email: "baher@business.com",
        ChatMemberIdentifier: "78470fc3-9c57-47e2-a73c-c3f97e6c2b71",
        ID: 404,
        Role: 4,
        IsDeleted: false,
        LastLoginDateTime: "2021-01-07T16:24:12.66",
        Relationship: "Adviser",
      },
      {
        $id: "10",
        HasFirstNameAndLastName: false,
        Name: "stone",
        AvatarToken: null,
        Mobile: null,
        Email: "ston22e@white.com",
        ChatMemberIdentifier: "cb6a54b1-f863-4a24-8b17-4f3a0c6308a9",
        ID: 497,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Wife",
      },
      {
        $id: "11",
        HasFirstNameAndLastName: true,
        Name: "baher staff 1",
        AvatarToken: null,
        Mobile: null,
        Email: "baher.staff1@business.com",
        ChatMemberIdentifier: "4b925a72-88be-4f23-b96f-ebc23442eb82",
        ID: 498,
        Role: 4,
        IsDeleted: false,
        LastLoginDateTime: "2020-10-27T18:21:44.25",
        Relationship: "Bookkeeper",
      },
      {
        $id: "12",
        HasFirstNameAndLastName: false,
        Name: "Nolast",
        AvatarToken: null,
        Mobile: null,
        Email: "nolast@white.com",
        ChatMemberIdentifier: "4c5f4d66-4a7f-4749-aa67-63b522b91a31",
        ID: 499,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Wife",
      },
      {
        $id: "13",
        HasFirstNameAndLastName: false,
        Name: "3",
        AvatarToken: null,
        Mobile: null,
        Email: "33@33.com",
        ChatMemberIdentifier: "98f65f4c-4e6a-4d25-b549-a963c80354b3",
        ID: 500,
        Role: 4,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Adviser",
      },
      {
        $id: "14",
        HasFirstNameAndLastName: true,
        Name: "black new",
        AvatarToken: null,
        Mobile: null,
        Email: "black.new@pro.com",
        ChatMemberIdentifier: "a081a1e4-cdb0-4149-b66d-156a126fd490",
        ID: 501,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: "2020-08-31T16:02:11.627",
        Relationship: "Other (personal team member)",
      },
      {
        $id: "15",
        HasFirstNameAndLastName: true,
        Name: "stone 1029",
        AvatarToken: null,
        Mobile: null,
        Email: "stone.1029@white.com",
        ChatMemberIdentifier: "b9f61a54-1938-43ed-8a92-f97c5bf721c7",
        ID: 502,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Family member",
      },
      {
        $id: "16",
        HasFirstNameAndLastName: true,
        Name: "black new",
        AvatarToken: null,
        Mobile: null,
        Email: "black.new@white.com",
        ChatMemberIdentifier: "bb404db4-2d40-412e-834a-9eaf1c605c87",
        ID: 503,
        Role: 4,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Accountant",
      },
      {
        $id: "17",
        HasFirstNameAndLastName: true,
        Name: "black pro new",
        AvatarToken: null,
        Mobile: null,
        Email: "black.pro.1029@white.com",
        ChatMemberIdentifier: "f497bb97-7675-4721-bc4d-d1a2e8d184f3",
        ID: 504,
        Role: 3,
        IsDeleted: false,
        LastLoginDateTime: null,
        Relationship: "Parent",
      },
    ],
  },
  HttpStatusCode: 200,
  Message: "",
};
